
package com.products.store2.jaxws;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;

/**
 * This class was generated by Apache CXF 3.1.8
 * Tue Dec 06 13:07:21 IST 2016
 * Generated source version: 3.1.8
 */

@XmlRootElement(name = "getAllProductsResponse", namespace = "http://store2.products.com/")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "getAllProductsResponse", namespace = "http://store2.products.com/")

public class GetAllProductsResponse {

    @XmlElement(name = "return", namespace = "http://store2.products.com/")
    private java.util.List<com.products.store2.product> _return;

    public java.util.List<com.products.store2.product> getReturn() {
        return this._return;
    }

    public void setReturn(java.util.List<com.products.store2.product> new_return)  {
        this._return = new_return;
    }

}

